### ISSUE TITLE
Needs a Text Editor

### ISSUE THREAD

**Issue by interfect** [interfect/bbfs#3]
Now that we support communicating with running applications (and that we expose the filesystem), we should have a text editor.

@orlof may have one.

**Comment by orlof** [comment]
has a Test Editor :)

**Comment by interfect** [comment]
I've put it in the 3.1 release image!

I have managed to crash it on Lettuce. And also on my emulator (which doesn't quite implement all of the LEM spec). I'll see if I can find a reproducible problem.
