### ISSUE TITLE
DCDOS_FILE_READ returns size=512 for zero length file

### ISSUE THREAD

**Issue by orlof** [interfect/bbfs#4]
I am not 100% sure about this, but could you verify?

1. DCDOS_SHELL_OPEN for not existing filename and create=1
2. Close emulator
3. DCDOS_SHELL_OPEN for the same file (now it exists, verified with dir) and create=1
4. DCDOS_FILE_READ for the same file with size=2048

For some reason FILE_READ returns error code 8 end of file and size 512. I expected to get size 0.

**Comment by interfect** [comment]
Did you sync the file before killing the emulator? If the file isn't
properly closed (with a sync) it might be that the used word count of the
final sector isn't committed to disk.

**Comment by orlof** [comment]
Ok, I was expecting fopen like semantics with atomic file creation. I'll test by adding FLUSH after OPEN and see what happens. 

Thanks!

**Comment by interfect** [comment]
We ought to have those. I'll work on it.

**Comment by orlof** [comment]
if I open an existing file to overwrite the contents. should i call OPEN -> TRUNCATE -> WRITE -> FLUSH?

**Comment by interfect** [comment]
Yes, unless you're certain the new data is longer than the old data.
