### ISSUE TITLE
DC-DOS does not restore videoram address when program returns

### ISSUE THREAD

**Issue by orlof** [interfect/bbfs#5]
There is no proper workaround as application program has no way to query original videoram address.

Currently solved with magical:

    set a, 0
    set b, 0xee80
    hwi [monitor]

**Comment by orlof** [comment]
Same goes also for font ram and palette ram, but those could be left for application programs responsibility as it can restore default font and palette just by setting the addresses to zero.

**Comment by interfect** [comment]
BBOS is responsible for managing VRAM for DC-DOS. It sets VRAM every time you call its output functions: https://github.com/MadMockers/BareBonesOS/blob/master/src/video.asm

So VRAM is supposed to be getting set back when the next prompt is printed. I'm not sure why it isn't. Do you have an example binary I can reproduce the issue with?

Your magic code should always work, assuming you're running on normal BBOS. You could also try getting the BBOS info and subtracting the VRAM size from the BBOS start address to get the start address of the BBOS VRAM.

Maybe you can print a goodbye message with the normal BBOS printing functions, and that will set VRAM back?

**Comment by orlof** [comment]
hmm, i did more testing with this and now it seems to work. it must have been some other problem in my setup.

This is not a bug.
